added authentication and authorization documentations
dotkernel/api-documentation pull request #25
Opened 2024-05-31 17:29 UTC by cPintiuta

2024-06-01 05:20 UTC, alexmerlin requested changes

2024-06-01 05:20 UTC, alexmerlin commented on docs/book/v4/core-features/authentication.md
> +DotKernel's API provides the ability to refresh the access token, generating a new one.
```suggestion
DotKernel API provides the ability to refresh the access token, by generating a new one using the expired access token's `refresh_token`.
```

2024-06-01 05:20 UTC, alexmerlin commented on docs/book/v4/core-features/authorization.md
> +The authorization happens through the middleware in the `Api\App\Middleware\AuthorizationMiddleware`.
```suggestion
The authorization happens through the `Api\App\Middleware\AuthorizationMiddleware` middleware.
```

2024-06-01 05:20 UTC, alexmerlin commented on docs/book/v4/core-features/authorization.md
> +In DotKernel API make use of `mezzio-authorization-rbac` and upon installation all the configuration is already made
```suggestion
DotKernel API makes use of `mezzio-authorization-rbac` and upon installation all the configuration is already made
```

2024-06-01 05:20 UTC, alexmerlin commented on docs/book/v4/core-features/authorization.md
> +The configuration where you define roles and permission is hold on `config/autoload/authorization.global.php`
```suggestion
The configuration file for the role and permission definitions is `config/autoload/authorization.global.php`.
```

2024-06-01 05:20 UTC, alexmerlin commented on docs/book/v4/core-features/authorization.md
> +        'roles'       => [
Decrease indentation starting for lines 25-53.

2024-06-01 05:20 UTC, alexmerlin commented on docs/book/v4/core-features/authorization.md
> +> You can check [mezzio-authorization-rbac](https://docs.mezzio.dev/mezzio-authorization-rbac/v1/basic-usage/) for more
```suggestion
> See [mezzio-authorization-rbac](https://docs.mezzio.dev/mezzio-authorization-rbac/v1/basic-usage/) for more information.
```

2024-06-01 05:20 UTC, alexmerlin commented on docs/book/v4/core-features/authorization.md
> +> in depth
```suggestion
```

2024-06-01 05:20 UTC, alexmerlin commented on docs/book/v4/core-features/authorization.md
> +A role can inherit the roles of their parent:
```suggestion
Roles inherit the permissions from their parents:
```

2024-06-01 05:20 UTC, alexmerlin commented on docs/book/v4/core-features/authorization.md
> +For each role we defined an array of permissions. A permission in DotKernel's is basically a route name.
```suggestion
For each role we defined an array of permissions. A permission in DotKernel API is basically a route name.
```

2024-06-01 05:20 UTC, alexmerlin commented on docs/book/v4/core-features/authorization.md
> +As you can see, the `superuser` does not have any permission, because inherit all the permission from `admin`no
```suggestion
As you can see, the `superuser` does not have it's own permissions, because it inherits all the permissions from `admin`, no
```

2024-06-01 05:20 UTC, alexmerlin commented on docs/book/v4/core-features/authorization.md
> +need to define permission for him again.
```suggestion
need to define permissions for it unless necessary.
```

2024-06-01 05:20 UTC, alexmerlin commented on docs/book/v4/core-features/authorization.md
> +The `user` role, inherit all the permission from `guest` so no need to define that `user` can access `home` route, but
```suggestion
The `user` role, inherits all the permission from `guest` so no need to define that `user` can access `home` route, but
```

2024-06-01 05:20 UTC, alexmerlin commented on docs/book/v4/core-features/authorization.md
> +`guest` cannot access `user.my-account.view` route.
```suggestion
`guest` cannot access user-specific routes.
```

2024-06-01 05:20 UTC, alexmerlin commented on docs/book/v4/core-features/authentication.md
> +DotKernel's API identities are delivered to the application from the client through the `Authorization` request
```suggestion
DotKernel API identities are delivered to the application from the client through the `Authorization` request
```

2024-06-01 05:20 UTC, alexmerlin commented on docs/book/v4/core-features/authentication.md
> +DotKernel's API assigns a default `guest` identity, represented by an instance of the class
```suggestion
DotKernel API assigns a default `guest` identity, represented by an instance of the class
```

2024-06-03 13:36 UTC, alexmerlin approved these changes

2024-06-03 16:01 UTC, arhimede approved these changes

2024-06-03 16:02 UTC, merged